#include <iostream>
#include <cstdlib>
#include <string>
#include <regex>
#include <exception>
#include <list>
#include <fstream>
//#include <stack>

#include <dirent.h>
#include <sys/types.h>
#include <sys/cdefs.h>
#include <sys/time.h>
#include <sys/resource.h>
#include <err.h>
#include <md5.h>
#include <ripemd.h>
#include <sha.h>
#include <sha256.h>
#include <sha512.h>
#include <time.h>
#include <unistd.h>
#include <string.h>

#include <sys/sysctl.h>
#include <sys/stat.h>
#include <strings.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <getopt.h>
